/**
 * @copyright 2020-2024 integereleven. All rights reserved. MIT license.
 * @file Exports public types from the module.
 */

export { ComparisonResult, ListPosition, Parity } from './enums.ts';

export type {
  IHashable,
  IHelpful,
  IVersionDescriptor,
  TBase,
  TCloneable,
  TComparable,
  TComparer,
  TConverter,
  TConvertible,
  TSortable,
} from './interfaces.ts';

export type {
  Action,
  AnyArray,
  AnyObject,
  Binary,
  BitValue,
  Clean,
  Comparer,
  ComparerFn,
  Constructor,
  Converter,
  ConverterFn,
  Couple,
  DecoratorTarget,
  Dyadic,
  Empty,
  Func,
  HexValue,
  IndeterminateObject,
  IsAny,
  IsNever,
  IsUnknown,
  KeyOfAny,
  MaybeArray,
  MaybeCalculated,
  MaybePromise,
  Monadic,
  Native,
  Nil,
  Nilable,
  Niladic,
  Nullable,
  Nullary,
  Octonary,
  Octuple,
  OrderedPair,
  Paths,
  PathValue,
  PredicateAction,
  PredicateFunc,
  Primitive,
  PrimitiveKey,
  PropertyValue,
  Quadruple,
  Quaternary,
  Quinary,
  Quintuple,
  ReducerFunc,
  Register,
  SafeRegister,
  Scalar,
  Senary,
  Septenary,
  Septuple,
  Sextuple,
  Single,
  Singleton,
  SystemArchitecture,
  SystemOS,
  Ternary,
  Tetradic,
  Triadic,
  Triple,
  Unary,
} from './type_aliases.ts';
